title: Wouter on Architecture
description: Random musings mostly on (Cloud) Architecture, Azure and .NET
url: https://woutervanranst.github.io
baseurl: /wouteronarchitecture.github.io
theme: null
permalink: pretty
markdown: kramdown
excerpt_separator: "<!--more-->"
