title: Wouter on Architecture
description: Random musings mostly on cloud architecture, Azure, and .NET.
url: https://woutervanranst.github.io
baseurl: ""
permalink: pretty
markdown: kramdown
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/posts/page:num/"

name: Wouter van Ranst
author: Wouter van Ranst
author_bio: Writing about architecture, distributed systems, Azure, and .NET.
cover: /assets/images/site-header.png
github_username: woutervanranst
linkedin_username: woutervanranst
